name: Test and build to github pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

# env:
#   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: npm install,build and test
        run: |
          npm ci
          npm test

      - name: Build to github pages
        run: npm run deploy

  # build:
  #   needs: test
  #   name: Build to github pages
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v2

  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: node-modules-artifacts
